add wave -noupdate -format Logic /testbnch/clk
add wave -noupdate -format Logic /testbnch/reset_n
add wave -noupdate -format Literal /testbnch/UARTstatus1_data_out
add wave -noupdate -format Logic /testbnch/UARTstatus1_parity_err
add wave -noupdate -format Logic /testbnch/UARTstatus1_overflow
add wave -noupdate -format Logic /testbnch/UARTstatus1_txrdy
add wave -noupdate -format Logic /testbnch/UARTstatus1_rxrdy
add wave -noupdate -format Literal /testbnch/UARTstatus2_data_out
add wave -noupdate -format Logic /testbnch/UARTstatus2_parity_err
add wave -noupdate -format Logic /testbnch/UARTstatus2_overflow
add wave -noupdate -format Logic /testbnch/UARTstatus2_txrdy
add wave -noupdate -format Logic /testbnch/UARTstatus2_rxrdy
add wave -noupdate -format Logic /testbnch/UARTconfig1_bit8
add wave -noupdate -format Logic /testbnch/UARTconfig1_parity_en
add wave -noupdate -format Logic /testbnch/UARTconfig1_odd_n_even
add wave -noupdate -format Logic /testbnch/UARTconfig2_bit8
add wave -noupdate -format Logic /testbnch/UARTconfig2_parity_en
add wave -noupdate -format Logic /testbnch/UARTconfig2_odd_n_even
add wave -noupdate -format Literal /testbnch/cpucontrol_data
add wave -noupdate -format Literal /testbnch/cpudata
add wave -noupdate -format Logic /testbnch/txdata1
add wave -noupdate -format Logic /testbnch/rxdata1
add wave -noupdate -format Logic /testbnch/txdata2
add wave -noupdate -format Logic /testbnch/rxdata2
